### ISSUE TITLE
Orphan stream name representation

### ISSUE THREAD

**Issue by otofoto** [christian-intra2net/oledump#2]
Orphan streams are not correctly named seems there is some issue with format('/'.join(st_path),
                              ' (orphan)' if is_orphan else '')

Checking stream "♣/S/u/m/m/a/r/y/I/n/f/o/r/m/a/t/i/o/n" (orphan)
Checking stream "♣/D/o/c/u/m/e/n/t/S/u/m/m/a/r/y/I/n/f/o/r/m/a/t/i/o/n" (orphan)
Checking stream "♣/S/e/b/i/e/s/n/r/M/k/u/d/r/f/c/o/I/a/a/m/t/y/k/d/D/a" (orphan)

**Comment by christian-intra2net** [comment]
Should be fixed now. Could you update and try again?

**Comment by otofoto** [comment]
Seems to be fixed.
